/**
 * @file    eslint.config.mjs
 * @purpose Flat ESLint config for Aria (ESLint 8.57 + eslint-config-next 15 via FlatCompat).
 *          Generated by next-lint-to-eslint-cli codemod, repaired for ESLint 8 compatibility.
 */

import { FlatCompat } from "@eslint/eslintrc";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "coverage/**",
    ],
  },
];

export default eslintConfig;
