db-uri = "postgresql://aria:arialocal@localhost:5433/aria"
db-schemas = "public,storage"
db-anon-role = "anon"
jwt-secret = "aria-local-dev-secret-not-for-production"
db-extra-search-path = "public"
max-rows = 1000
server-port = 5434
server-host = "127.0.0.1"
openapi-server-proxy-uri = "http://localhost:5434"