-- Tracks prescriptive reorder/build alerts generated by the smart alert engine.
-- One row per (sku, alert_type) — upserted on each run so alerted_at stays fresh.
-- Dedup logic: only re-alert if risk_level worsened OR alerted_at > 20h ago.

CREATE TABLE IF NOT EXISTS proactive_alerts (
  id                uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  sku               text NOT NULL,
  alert_type        text NOT NULL DEFAULT 'reorder',   -- 'reorder' | 'build'
  risk_level        text NOT NULL,                     -- 'CRITICAL' | 'WARNING'
  stockout_days     integer,
  suggested_order_qty integer,
  days_after_order  integer,
  alerted_at        timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
  CONSTRAINT proactive_alerts_sku_type_unique UNIQUE (sku, alert_type)
);

CREATE INDEX IF NOT EXISTS idx_proactive_alerts_alerted_at ON proactive_alerts (alerted_at DESC);

ALTER TABLE proactive_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for service role" ON proactive_alerts
  USING (true) WITH CHECK (true);

COMMENT ON TABLE proactive_alerts IS
  'Smart reorder/build prescriptions generated by the Aria reorder engine. Drives dedup for Telegram alerts.';
